### ISSUE TITLE
Import bootstrap and other vendor files

### ISSUE THREAD

**Issue by wreyniers** [bythepixel/kyrio-go2broadband#17]
@polydegmon 
- [x] Bootstrap
- [x] UI Javascript
- [x] Custom CSS
- [x] Add Kyrio html updates

@NathanBurkett 
- [ ] Handle LESS files

**Comment by polydegmon** [comment]
# **Folder Structure**

We currently have our css and images under a Content folder and our javascript files under a Scripts folder

**Here's the break down of the folders and their contents**

## **Content Folder** [Site Content, Images, Styles, By The Pixel Items]

- css [3rd party style sheets + By The Pixel Items]
- css/Locator [Custom styles for the site]	

- DatePicker [Third party calendar tool - Nuget Package]

- favicon [By The Pixel Items]

- Fonts [Bootstrap glyph icon files + By The Pixel Items]
- Fonts/argentcf [By The Pixel Items]
- Fonts/proximanova [By The Pixel Items]
- Fonts/realtime [By The Pixel Items]

- Images [Images for the website]
- Images/MsoLogos [Mso (Cable Operator) Logos]

- js [By The Pixel Items]

- media [By The Pixel Items]

- bootstrap-config.json [Custom bootstrap settings for site]

## **Scripts Folder** [Scripts Folder Structure]

- Scripts [3rd party scripts]
- Scripts/Locator [Custom scripts for the site]

**Comment by polydegmon** [comment]
# Razor Model Binding

Due to the way this is implemented we need to have control over the name attribute for the elements rendered on the page.

## Razor Model Binding Explanation
Model binding works by binding the key/value pairs sent by the browser in a form post to model properties (or view data). A form input's name attribute is what is used as its key in the form data submitted in a POST request.

When you use HTML helpers to render form fields, the framework automatically generates the appropriate name attributes required to ensure that the field will bind properly to the property specified in the expression you pass to the helper.

If you change the name, you break the only connection between the form input and the property it binds to.

**Comment by polydegmon** [comment]
I've added our relevant folders and checked it into the KyrioContent branch

I'll issue a pull request once Nathan and I clarify some items.

**Comment by polydegmon** [comment]
**I've added 2 branches**

### Branch : KyrioContent

- This branch contains our css, media and javascript files.
- Our media and css can be found in the Content folder
- Our javascript files can be found in the Scripts folder
- I have just added these folders and files to the project in this branch. I have left Nathans' files as is.

### Branch : PixelAndKyrioContentCombined

- This branch contains a combined project.
- I have moved all the relevant files into our folder structure
- I have also added a views folder, this contains our razor views, I have added the views that I think you would be working on. More of our razor views can be added here as needed
- I have updated index.html and created 2 files from it
- **index_original.html** : This is Nathans' original file, no changes have been made to this other than path changes to get all the media, css and scripts to load
- **index_kyrio.html** : This contains all the changes we have made to the index_original.html file


**index_kyrio.html : This is the most current file, it includes everything that we have done and is in a working state**
